version: '3.8'

services:
  minecraft-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-forge-server
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "25565:25565/udp"
    volumes:
      - ./server-data:/minecraft
    environment:
      - MINECRAFT_VERSION=1.21.1
      - FORGE_VERSION=47.4.0
      - EULA=TRUE
      - MAX_MEMORY=4G
      - MIN_MEMORY=2G
    tty: true
    stdin_open: true

networks:
  default:
    name: minecraft-network
