[forge.server]
  # Requires players to have a modified client to play on the server
  requireClientVersions = false
  
  # Disable the ability for Forge to update the world format
  # WARNING: May cause the mod to not work at all
  disableWorldFormatUpdate = false

[forge.mods.coreprotect]
  # If enabled, server operators will have the '#coreprotect' command permission by default
  operatorPermission = true
  
  # If enabled, server operators will be allowed to use the entire CoreProtect command syntax
  fullOperatorAccess = true

[forge.mods.default_permissions]
  # Default permission level for all players (0-4)
  # 0 = no permissions, 4 = full operator
  defaultPermissionLevel = 4
  
  # Minimum operator level required
  minimumOpLevel = 0
  
  # Permission level for operators
  operatorPermissionLevel = 4
